/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAgenteImpressaoRouteImport } from './routes/_authenticated/agente-impressao'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEditorRouteImport } from './routes/_authenticated/editor'
import { Route as AuthenticatedAdminAuditoriaRouteImport } from './routes/_authenticated/admin/auditoria'
import { Route as AuthenticatedAdminSetoresRouteImport } from './routes/_authenticated/admin/setores'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedDocumentosEditorIndexRouteImport } from './routes/_authenticated/documentos/editor/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgenteImpressaoRoute =
  AuthenticatedAgenteImpressaoRouteImport.update({
    id: '/agente-impressao',
    path: '/agente-impressao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditorRoute = AuthenticatedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditoriaRoute =
  AuthenticatedAdminAuditoriaRouteImport.update({
    id: '/admin/auditoria',
    path: '/admin/auditoria',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminSetoresRoute =
  AuthenticatedAdminSetoresRouteImport.update({
    id: '/admin/setores',
    path: '/admin/setores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentosEditorIndexRoute =
  AuthenticatedDocumentosEditorIndexRouteImport.update({
    id: '/editor/',
    path: '/editor/',
    getParentRoute: () => AuthenticatedDocumentosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agente-impressao': typeof AuthenticatedAgenteImpressaoRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/editor': typeof AuthenticatedEditorRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/documentos/editor/': typeof AuthenticatedDocumentosEditorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agente-impressao': typeof AuthenticatedAgenteImpressaoRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/editor': typeof AuthenticatedEditorRoute
  '/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/documentos/editor': typeof AuthenticatedDocumentosEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agente-impressao': typeof AuthenticatedAgenteImpressaoRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRouteWithChildren
  '/_authenticated/editor': typeof AuthenticatedEditorRoute
  '/_authenticated/admin/auditoria': typeof AuthenticatedAdminAuditoriaRoute
  '/_authenticated/admin/setores': typeof AuthenticatedAdminSetoresRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/documentos/editor/': typeof AuthenticatedDocumentosEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agente-impressao'
    | '/biblioteca'
    | '/documentos'
    | '/editor'
    | '/admin/auditoria'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/documentos/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agente-impressao'
    | '/biblioteca'
    | '/documentos'
    | '/editor'
    | '/admin/auditoria'
    | '/admin/setores'
    | '/admin/usuarios'
    | '/documentos/editor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agente-impressao'
    | '/_authenticated/biblioteca'
    | '/_authenticated/documentos'
    | '/_authenticated/editor'
    | '/_authenticated/admin/auditoria'
    | '/_authenticated/admin/setores'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/documentos/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agente-impressao': {
      id: '/_authenticated/agente-impressao'
      path: '/agente-impressao'
      fullPath: '/agente-impressao'
      preLoaderRoute: typeof AuthenticatedAgenteImpressaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/editor': {
      id: '/_authenticated/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthenticatedEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/auditoria': {
      id: '/_authenticated/admin/auditoria'
      path: '/admin/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/setores': {
      id: '/_authenticated/admin/setores'
      path: '/admin/setores'
      fullPath: '/admin/setores'
      preLoaderRoute: typeof AuthenticatedAdminSetoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos/editor/': {
      id: '/_authenticated/documentos/editor/'
      path: '/editor'
      fullPath: '/documentos/editor/'
      preLoaderRoute: typeof AuthenticatedDocumentosEditorIndexRouteImport
      parentRoute: typeof AuthenticatedDocumentosRoute
    }
  }
}

interface AuthenticatedDocumentosRouteChildren {
  AuthenticatedDocumentosEditorIndexRoute: typeof AuthenticatedDocumentosEditorIndexRoute
}

const AuthenticatedDocumentosRouteChildren: AuthenticatedDocumentosRouteChildren =
  {
    AuthenticatedDocumentosEditorIndexRoute:
      AuthenticatedDocumentosEditorIndexRoute,
  }

const AuthenticatedDocumentosRouteWithChildren =
  AuthenticatedDocumentosRoute._addFileChildren(
    AuthenticatedDocumentosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgenteImpressaoRoute: typeof AuthenticatedAgenteImpressaoRoute
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRouteWithChildren
  AuthenticatedEditorRoute: typeof AuthenticatedEditorRoute
  AuthenticatedAdminAuditoriaRoute: typeof AuthenticatedAdminAuditoriaRoute
  AuthenticatedAdminSetoresRoute: typeof AuthenticatedAdminSetoresRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgenteImpressaoRoute: AuthenticatedAgenteImpressaoRoute,
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRouteWithChildren,
  AuthenticatedEditorRoute: AuthenticatedEditorRoute,
  AuthenticatedAdminAuditoriaRoute: AuthenticatedAdminAuditoriaRoute,
  AuthenticatedAdminSetoresRoute: AuthenticatedAdminSetoresRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
